### ISSUE TITLE
[Suggestion] Incorporate the content of "Efficient UUIDs" into this one?

### ISSUE THREAD

**Issue by jpmurray** [michaeldyrynda/laravel-model-uuid#1]
Or vice versa? I can see why you would separate the two packages, but I think it's nothing one or two quick config value couldn't solve?

Like, only overrides the grammar if a config value is set to true and connection type is mysql?

It's absolutely not a deal breaker having those two separate, mind you! I'm just throwing the idea out in the wild ;-)

**Comment by michaeldyrynda** [comment]
I left it out only because it's just for MySQL (at this stage). As the functionality is required elsewhere, I'll consider merging the two packages.

For now, this package is just to make it easier to use UUIDs in your models without having to worry about how they're being stored in the database, so you can keep using Laravel's default (`char(36)`).

Through some more work I did on this today, I've discovered it's not a simple case of changing between CHAR and BINARY and don't want to make a mess of people's data 👍

**Comment by jpmurray** [comment]
Perfect! ;-)
