### ISSUE TITLE
Conflict with latest ramsey/uuid version 3.7

### ISSUE THREAD

**Issue by damosse31** [michaeldyrynda/laravel-model-uuid#37]
Hi Michael !

just to inform that the latest v3.7 of ramsey/uuid released but when tried to update, this is what composer replied : 

_dyrynda/laravel-model-uuid 2.0.3 requires ramsey/uuid 3.6.* -> satisfiable by ramsey/uuid[3.6.0, 3.6.1] but these conflict with your requirements or minimum-stability._

**Comment by michaeldyrynda** [comment]
Is this because you're using 3.7 explicitly in your own project? I think that's why you're getting the conflict - I'll have to do some testing with 3.7 after looking at what's changed between it and 3.6.

**Comment by damosse31** [comment]
I confirm I have "ramsey/uuid": "^3.6" in my composer.json

But the problem is when I try to update to v3.7 composer don't want because your package require v3.6 maximum for ramsey package.

Or maybe I have something wrong ? :)

**Comment by michaeldyrynda** [comment]
Yeah, `^3.6` will update `>= 3.6` up to but not including `4.*`, but because this package requires 3.6.*, you won't be able to update.

Doesn't look like there's any [significant changes](https://github.com/ramsey/uuid/compare/3.6.1...3.7.0) between the two most recent releases. I'll have a look at relaxing the constraint in this package so it's easier to update `ramsey/uuid` in future a bit later on.

**Comment by damosse31** [comment]
Thanks michael I wait for the next release 👍
