### ISSUE TITLE
Event::fake(), model factories and uuid field

### ISSUE THREAD

**Issue by avvertix** [michaeldyrynda/laravel-model-uuid#64]
I experienced a strange scenario during the creation of a unit test that use `Event::fake()` and model factories with model having a non nullable `uuid` field (stored using the `bytes` data type). I don't think it as bug, but probably something worth mentioning (or me just been stupid).

I used to put `Event::fake()` at the beginning of a test and then creating the models to use in the test.

```php
public function test_example()
{
    Event::fake();
    $user = factory(User::class)->create();
}
```
The UserFactory has only the addition of the uuid field to generate

```php
$factory->define(User::class, function (Faker $faker) {
    return [
        // ...
        'uuid' => $faker->uuid,
        // ...
    ];
});
```

Then I started experiencing this error:

```
Illuminate\Database\QueryException: SQLSTATE[22001]: 
String data, right truncated: 1406 Data too long for 
column 'uuid' at row 1
```
(from the whole exception message it is to note that the uuid is written as string)

After some time I realized that the generation of the uuid happen using the `creating` eloquent event and so faking all events disabled that behavior entirely and the solution to my problem was faking the events after model creation (or maybe better fake only the event I was looking for).

```
$user = factory(User::class)->create();

Event::fake(); // or Event::fake([TheEvent::class])
```

**Comment by Gummibeer** [comment]
It seems like the problem isn't the auto-created UUID but the missing casting? Couldn't it be an idea to use accessor/mutator for this?
At least with Laravel 7 we will get custom casts https://github.com/laravel/framework/pull/31035

**Comment by Synchro** [comment]
I'm running into this problem in a different way, and I'm not sure how I can work around it as suggested in this thread. I'm testing an API endpoint that creates a UUID model inside its controller. This controller also emits an event that I want to test for, so I'm calling `Event::fake()` and have an `assertDispatched` in my test. Because the resource is cerated within the API and not in the test, I don't have the opportunity to create the resource prior to calling the API (the solution suggested here). like this:

```php
        Event::fake();
        $response = $this->postJson(
            '/retail/checkout',
            [
                ...
            ]
        );
        $response->assertStatus(Response::HTTP_CREATED);
        Event::assertDispatched(\App\Events\CollectionOrdered::class);
```
The net result is that the test fails because the UUID property ends up empty because the internal event that creates it is suppressed.

I don't get @Gummibeer's note about casting – I'm not casting the `uuid` property, and I'm not using `EfficientUuid`; is casting necessary since it's just a string?

How should I arrange this to be able to test my event without breaking UUID generation?

**Comment by Gummibeer** [comment]
I'm not sure what my answer was about. 😅
But some of the facades (all?) allow to `spy()` instead of `fake()`. Which will make the facade behave like normal but you can use the mock methods like `shouldReceive()`.

We used it in yesterday's stream to do some more complex assertions on queue jobs.
https://twitter.com/LukeDowning19/status/1440774206434672645?s=19

**Comment by avvertix** [comment]
@Synchro If I understood correctly you are only interested in one specific event and the others should keep be handled. In this case you can [fake specific events](https://laravel.com/docs/8.x/mocking#faking-a-subset-of-events) with

```php
Event::fake([
    \App\Events\CollectionOrdered::class,
]);
```

**Comment by michaeldyrynda** [comment]
Either of @Gummibeer or @avvertix solutions should do the trick.

Personally I have taken the approach where I fake the specific event only, seeing as that is the only event you are interested in testing against.

**Comment by Synchro** [comment]
Thank you all very much! I didn't know about `spy`, nor about `fake` having the ability to be selective.

**Comment by Gummibeer** [comment]
The major difference is that faking a specific event still prevents it listeners being executed.
Which can become problematic in some cases when you want to test event and listener.

Spy only sits on the line and spies everything coming by but doesn't touch it. So everything runs like on production but is recorded.
