### ISSUE TITLE
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

### ISSUE THREAD

**Issue by Sammyjo20** [michaeldyrynda/laravel-model-uuid#66]
Hey 👍

Thanks for the great Laravel Package. Just noticed this composer error while installing my dependencies. Thought I'd let you know. 😊

**Comment by atymic** [comment]
Looks like it's not a straight forward move:
https://github.com/brick/math

**Comment by michaeldyrynda** [comment]
Happy to review a PR with the necessary changes!

I believe @ramsey is working on `ramsey/uuid` 4.0 at the moment, which makes this change for us upstream, so may be necessary for a final release there.

**Comment by ramsey** [comment]
Technically, it's not an *error*. It's a warning. 😉

I'm also the maintainer of moontoast/math, and I'll no longer be developing it. There are better, more full-featured arbitrary precision math libraries available, such as brick/math. You may continue to use moontoast/math, but it won't receive any more updates.

The reason moontoast/math is required for Laravel is because Laravel uses the `TimestampFirstCombCodec`, which requires moontoast/math  (see [here](https://github.com/laravel/framework/blob/46993808273ffaf859d03f2172db3625e9dfb6e6/src/Illuminate/Support/Str.php#L638-L661)).

Version 4 of ramsey/uuid no longer uses moontoast/math, and the upgrade should be seamless for most uses of ramsey/uuid (including Laravel's—I've tested this thoroughly!). A pre-release version (4.0.0-alpha1) is available here: https://github.com/ramsey/uuid/releases/tag/4.0.0-alpha1

Cheers!
