### ISSUE TITLE
Route custom keys & scoping not working with uuid

### ISSUE THREAD

**Issue by parth391** [michaeldyrynda/laravel-model-uuid#98]
Hello,

I am trying to use route custom keys & scoping as bellow, but getting 404.

`Route::get('users/{user:uuid}/edit', 'UsersController@edit')->name('users.edit')`

Is there any to convert uuid to binary uuid, before type-hitting?

**Comment by kevindb** [comment]
@parth391 I think your issue is that the [_implicit_ route model binding](https://laravel.com/docs/8.x/routing#implicit-binding) is taking the UUID string literally, whereas the query needs the binary version of the UUID.
I ran into the exact problem you did. The only way I could fix it was by using [_explicit_ route model binding](https://laravel.com/docs/8.x/routing#explicit-binding). Add this to your `app/Providers/RouteServiceProvider@boot` (updating to your key name and model, of course):

```
Route::bind('deal', function ($value) {
    return \App\Models\Deal::whereUuid($value)->first();
});
```

The downside is that you have to add those three lines for each and every route bound to that Model.

------

@michaeldyrynda Is there some other way of referencing the `uuid` attribute that we're not seeing? In my idea world, I'd be able to use the string form of the UUID (`418a5383-6134-42fd-bd5d-4d838c3dfe96`) in the PHP code and have it automagically cast/convert to the binary form behind the scenes, where I never have to see it.

For example, this does not work, because it is similarly querying with the UUID string instead of the UUID binary.

```
Deal::whereNotIn('uuid', ['1eaf88f1-dd8d-60ba-9780-080027718adf','906eaba3-1053-43f1-8c04-4be57b08598f'])->get()
```
```
[
    "query" => "select * from `deals` where `uuid` not in (?, ?)"
    "bindings" => [
        1 => "1eaf88f1-dd8d-60ba-9780-080027718adf"
        2 => "906eaba3-1053-43f1-8c04-4be57b08598f"
    ]
]
```

**Comment by ArtisanTinkerer** [comment]
This isn't working for me, can you see what is wrong:

```
Route::patch('/{thingl}'...................etc
```

Thing.php
```
public function getRouteKeyName()
    {
        return 'uuid';
    }
```

RouteServiceProvider
```
Route::bind('thing', function ($value) {
            return Thing::whereUuid($value)->first();
        });
```

test
```
$response = $this->patchJson(route('thing.update', $thing), $thing->toArray());
```

I get:

 "message": "No query results for model [App\\Models\\Thing] ae92f158-36a4-47c6-8bf4-2308c2a1df04"

**Comment by ArtisanTinkerer** [comment]
I got my binding working by adding this to the model:

```
public function resolveRouteBinding($value, $field = null)
    {
        $bytes = Uuid::fromString($value)->getBytes();
        return $this->where('uuid', $bytes)->firstOrFail();
    }
```
